// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPAPmmrNXTegCMMkDfpvVFQnH0Q22XlF0',
    appId: '1:373211068576:web:bd5e2e063f43c13b61f1c5',
    messagingSenderId: '373211068576',
    projectId: 'we-chat-36fc7',
    authDomain: 'we-chat-36fc7.firebaseapp.com',
    storageBucket: 'we-chat-36fc7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUWgILf5tC9TEfbRDxvJwLnDL-kOqJeTg',
    appId: '1:373211068576:android:ad96a2562ca2192a61f1c5',
    messagingSenderId: '373211068576',
    projectId: 'we-chat-36fc7',
    storageBucket: 'we-chat-36fc7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuxjQf--dVnNFV9duU6EDlSYEkCMH8weg',
    appId: '1:373211068576:ios:f6cb0d5414e9998061f1c5',
    messagingSenderId: '373211068576',
    projectId: 'we-chat-36fc7',
    storageBucket: 'we-chat-36fc7.appspot.com',
    iosBundleId: 'com.rahul.wechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuxjQf--dVnNFV9duU6EDlSYEkCMH8weg',
    appId: '1:373211068576:ios:d591f8929c6d3b1361f1c5',
    messagingSenderId: '373211068576',
    projectId: 'we-chat-36fc7',
    storageBucket: 'we-chat-36fc7.appspot.com',
    iosBundleId: 'com.rahul.wechat.RunnerTests',
  );
}
